### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by CoolerProYT** [KanadeSiina/pocket48-discord#1]
我的做法是
npm install
npm run build
npm run start

提问：env 里的account 是手机号吗？什么格式

然后就显示这个了
![image](https://github.com/KanadeSiina/pocket48-discord/assets/118531227/305b1b2f-db66-4fdf-8145-66ad72fbcae7)

**Comment by akamya997** [comment]
感谢你的关注。

关于env的设置，需要直接去访问后端的一些api来获取account。我目前也很没有找到很好的方式。

我稍候可以写一个简单的教程或者提供相关的脚本。

**Comment by CoolerProYT** [comment]
我有登录的token了，用api验证码登录的，但是env需要账号密码我就不确定是什么。
我等你的教程吧，谢谢

**Comment by akamya997** [comment]
> 我有登录的token了，用api验证码登录的，但是env需要账号密码我就不确定是什么。
> 我等你的教程吧，谢谢

既然你有登陆的token了，那你可以尝试访问下面这个api获取account
https://github.com/duan602728596/qqtools/blob/e55fffe45cdecf3b1c076194408d9046ffea11ff/packages/qqtools/src/services/48/login/index.ts#L54

这个account应该是口袋房间用的网易云信的账号

**Comment by CoolerProYT** [comment]
![image](https://github.com/KanadeSiina/pocket48-discord/assets/118531227/4f005f8b-1e32-4194-b75c-305d51647a6a)
每次到这里就没了， env的account我用了api给的accid,密码我试了口袋密码，token,和api给的密码

**Comment by akamya997** [comment]
status没问题的话应该就能跑起来了，account和pwd都是使用api给的。

你可以用`pm2 logs main`查看一下日志。

**Comment by CoolerProYT** [comment]
![image](https://github.com/KanadeSiina/pocket48-discord/assets/118531227/b52fef04-1a9e-452d-9540-8d1597b4a643)

**Comment by akamya997** [comment]
> ![image](https://github.com/KanadeSiina/pocket48-discord/assets/118531227/b52fef04-1a9e-452d-9540-8d1597b4a643)
> 

我在我的windows上测试了一下是可以运行的，你的node版本是多少呢？

另外，你可以先用`npm run test`进行调试。

**Comment by CoolerProYT** [comment]
v21.5.0
![image](https://github.com/KanadeSiina/pocket48-discord/assets/118531227/c9c0b30d-a6ed-4957-9e5c-0102c75a259a)
test也是一样的报错

**Comment by akamya997** [comment]
测试了一下好像是node21的问题，node20就能跑，我之后再研究一下

**Comment by CoolerProYT** [comment]
好的,换去node20能用了，谢谢
